[tasks.build]
command = "wasm-pack"
args = ["build", "--dev", "--target", "web", "--out-name", "wasm", "--out-dir", "./static"]

[tasks.restore1]
script = [
    "cp static_required/index.html static/"
]

[tasks.restore2]
script = [
    "cp static_required/styles.css static/"
]
[tasks.restore3]
script = [
    "cp -R static_required//products static/"
]

[tasks.serve]
command = "simple-http-server"
args = ["-i", "./static/", "-p", "3000", "--nocache", "--try-file", "./static/index.html"]

[tasks.my-flow]
dependencies = [
    "build",
    "restore1",
    "restore2",
    "restore3",
]